name: MISSDC_EXP_GRIMP
channels:
  - defaults
  - conda-forge
  - dglteam
dependencies:
  - python==3.10
  - pip
  - scikit-learn
  - scipy
  - setuptools
  - tqdm
  - numpy<2
  - pandas
  - gensim
  - seaborn
  - matplotlib
  - pybind11
  - toml
  - pydantic
  - pip:
    - chardet==5.2.0
    - fasttext-wheel
    - networkx==3.2.1
  - pre-commit
